### ISSUE TITLE
Error when no customer data attached

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-portal#16]
Page Cooperative -> Customer Data (user has the rights)
but no customer data actually attached -> Error

**Comment by liebhock** [comment]
Beim Anlegen einer neuen Genossenschaft im Active-Admin können direkt Customer-Data hochgeladen werden. Das braucht es nicht bzw. hat mich irritiert, dass das möglich ist.

**Comment by morris-frank** [comment]
@liebhock heißt nur ZIP upload? Dann kann man halt nicht im Notfall die Kundendaten einer einzelnen BEG aktualisieren...

**Comment by liebhock** [comment]
Im Zweifel können doch über den Kundendaten upload auch einzelne Dateien hochgeladen werden, oder?
Mir war es beim Erstellen einer neuen BEG aufgefallen. Dort ist es zumindest nicht notwendig. Stört im Zweifel aber auch nicht sehr. Ich schaue mir nochmal an, wo/wie die anderen Uploads aussehen. 

Am 18. Juli 2018 21:29:27 MESZ schrieb Maurice Frank <notifications@github.com>:
>@liebhock heißt nur ZIP upload? Dann kann man halt nicht im Notfall die
>Kundendaten einer einzelnen BEG aktualisieren...
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/morris-frank/buergerwerke-portal/issues/16#issuecomment-406047183

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
