### ISSUE TITLE
user cannot have same e-mail as admin

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-portal#21]
Ist das Absicht? - Ich brauche als admin bzw. jetzt eben als user eine andere E-Mailadresse.

**Comment by morris-frank** [comment]
Das ist, wenn notwendig, nicht minor :wink:

Die Modelle _Member_ und _Admin_ sind Kindermodelle der Tabelle _User_ (stehen also in der gleichen Tabelle in der Datenbank).

Da in dieser Tabelle die E-Mail ein Index ist, muss das eindeutig sein, deswegen kann es momentan nicht Admins und Member mit gleicher Mail geben
