### ISSUE TITLE
duplicates of Vorstände 

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-portal#22]
Wenn es im add board attr Vorstände gibt, die auch als user Vorstand sind, werden sie doppelt angezeigt in der Übersicht "Genossenschaft"

**Comment by liebhock** [comment]
Die Vorstände, die als user registriert sind, sind nicht als solche erkennbar --> user-Vorstände könnten verlinken zu members der Genossenschaft, dann würden sie als Link hervorgehoben werden.

**Comment by morris-frank** [comment]
fixed by in 9f1e936
