### ISSUE TITLE
link to url of cooperative-homepage invalid

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-portal#23]
Bei M0000 Bürgerwerke auf BEG-Profil: https://portal.buergerwerke.de/cooperatives/2
Wird der Linktext: www.buergerwerke.de 
richtig dargestellt. Die Ziel-url: https://portal.buergerwerke.de/cooperatives/www.buergerwerke.de
ist aber falsch.

**Comment by morris-frank** [comment]
38ee57c erzwingt Format http://.... dadurch kommt das nicht mehr vor
