### ISSUE TITLE
use correct orange colour for buttons / headings

### ISSUE THREAD

**Issue by liebhock** [morris-frank/buergerwerke-portal#27]
from Isa:
Mir ist aufgefallen, dass du nicht das „richtige“ Orange verwendest => Ich weiß aber nicht, was ihr diesbezüglich besprochen habt? Normal verwenden wir: #fab41a für gelb und  #f4950c für orange. Gelb nur für manche Überschriften, Buttons etc. orange. Im Frontend fände ich es gut, wenn es dann dem Taca angepasst ist.

**Comment by morris-frank** [comment]
Fixed by 7572ce9f67be35a360b2ab3671956be61cd54521
