### ISSUE TITLE
Active Admin: Auf Deutsch übersetzen

### ISSUE THREAD

**Issue by morris-frank** [morris-frank/buergerwerke-portal#6]

**Comment by liebhock** [comment]
Meldungen, wie "You didn't upload a file."
Oder Buttons wie: "Upload ZIP file" 
sind noch auf englisch

**Comment by liebhock** [comment]
Im Admin-Panel:
"Cooperative Details"
--> Projektnummer := "Mitgliedsnummer"
Feldbezeichnungen: Street, City

**Comment by morris-frank** [comment]
Fixed mit 4773794ed06abe1cdcec1e4ffbc646852e71d1e9 und 0a2735c65bed4e4208af33f7a82e9b42087f85b5
